version: 2.1

jobs:
  run-test:
    docker: 
      - image: mcr.microsoft.com/playwright:v1.23.1-focal
    steps:
      - checkout
      - run: npm i -D @playwright/test
      - run: npx playwright install
      - run: npx playwright install chrome
      - run:
          name: Run test
          command: npm run test
workflows:
  run-test-workflow:
    jobs:
      - run-test
