version: 2.1

orbs:
  node: circleci/node@4.7

workflows:
  sample:
    jobs:
      - node/test:
          version: '16.10'
          pkg-manager: npm
          steps:
            - run:
                name: Install Chromium for Playwright
                command: |
                  npm install -g playwright
                  npx playwright install chromium
            - run:
                name: Run tests with Playwright
                command: npm run test
